name: Linux Intel Test
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Linux Intel Build"]
    types:
      - completed
env:
    CI: false
jobs:
    test:
        runs-on: [self-hosted, Linux]
        steps:
            - name: Basic info
              run: |
                  echo "Build for ${{ github.ref }} branch in ${{ github.repository }} repository."
                  echo "Job triggered by ${{ github.event_name }}, on self-hosted ${{ runner.os }}."  
                    echo "Log level: ${{ github.event.inputs.logLevel }}"
                  echo "Tags: ${{ github.event.inputs.tags }}"
            - name: Check out repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Build 
              run: |
                  export FASP_DIR=/opt/faspsolver
                  chmod 755 cli
                  ./cli test -b Release -c intel