name: Release Publish

on:
  release:
    types: [published]
permissions:
  contents: read

jobs:
  create_pull_request:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Release ${{ github.event.release.tag_name }}
          body: Update changelog for ${{ github.event.release.tag_name }}
          branch: update-changelog